version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://crystalbay:password@db:5432/crystalbay_travel
      - PGHOST=db
      - PGPORT=5432
      - PGUSER=crystalbay
      - PGPASSWORD=password
      - PGDATABASE=crystalbay_travel
      - FLASK_SECRET_KEY=dev-secret-key-change-in-production
      - DEBUG=true
    depends_on:
      - db
    volumes:
      - .:/app
    restart: unless-stopped

  db:
    image: postgres:13-alpine
    environment:
      - POSTGRES_DB=crystalbay_travel
      - POSTGRES_USER=crystalbay
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data: